### ISSUE TITLE
Tópico <digite aqui o número do tópico>

### ISSUE THREAD

**Issue by marcus-ar** [plinioleitao/bd-2021-1-bgi#159]
**Qual o nome dos empregados que não possuem dependentes?**

**CPF_Funcionario_Geral** <- π CPF(FUNCIONARIO)
**CPF_Funcionario_Dependente** <- π fcpf(Dependente)
**CPF_Funcionario_Sem_Dependente** <- CPF_Funcionário_Geral – CPF_Funcionário_Dependente
**Result** <- Pnome, Unome CPF_Funcionario_Sem_Dependente(Funcionario)

**Qual o nome dos empregados que trabalham em pelo menos um projeto?**

**CPF_Geral** <- π cpf(Funcionario)
**Cpf_Trabalha_Projeto** <- π Fcpf(Trabalha_Em)
**CPF_Pelo_Menos_Um** <- CPF_Geral ∩ CPF_Trabalha_Projeto
**Result** <- Pnome, Unome CPF_Pelo_Menos_Um(Funcionario)

**Comment by plinioleitao** [comment]
Por favor, fique atento ao título da _issue_.
Questão 1: A expressão abaixo está correta?
Result <- Pnome, Unome CPF_Funcionario_Sem_Dependente(Funcionario)
Questão 2: A expressão abaixo está correta?
Result <- Pnome, Unome CPF_Pelo_Menos_Um(Funcionario)

Respostas:
1)
FUNC_SEM_DEP(Cpf) ← π Cpf (FUNCIONARIO) - π Fcpf (DEPENDENTE)
RESULT ← π Pnome, Unome (FUNCIONARIO * FUNC_SEM_DEP)
2)
RESULT ← π Pnome, Unome (FUNCIONARIO ⋈ Cpf = Fcpf TRABALHA_EM)
SEM APROVEITAMENTO
