### ISSUE TITLE
[Dúvida] Vídeos de apoio ao conteúdo

### ISSUE THREAD

**Issue by Igor-Neiva** [plinioleitao/bd-2021-1-bgi#203]
Link para os vídeos que uso para comparar a teoria:

https://www.youtube.com/playlist?list=PLHCyLhqWSaHCItIKsQ37d7-_1CIDlZUtf

@plinioleitao , quando tiver um tempo da uma olhada para ver se é interessante ou não, é uma playlist focada em Banco de Dados.

**Comment by plinioleitao** [comment]
Olá Igor, obrigado pela sugestão, irei divulgar nos _Avisos Ativos_ do portal da disciplina.
