### ISSUE TITLE
Tópico 19.

### ISSUE THREAD

**Issue by Luan-Alonso** [plinioleitao/bd-2021-1-bgi#273]
SELECT Pnome, Unome
FROM FUNCIONARIO JOIN DEPENDENTE ON Cpf = Fcpf
GROUP BY Pnome, unome
HAVING COUNT(Fcpf) >=2
INTERSECT
SELECT Pnome, Unome
FROM FUNCIONARIO JOIN TRABALHA_EM ON Cpf =Fcpf
GROUP BY Pnome, Unome
HAVING COUNT(Fcpf) >=2

**Comment by plinioleitao** [comment]
Se houver funcionários homônimos?
SEM APROVEITAMENTO.
