### ISSUE TITLE
Tópico <02>

### ISSUE THREAD

**Issue by Warleymartins** [plinioleitao/bd-2021-1-bgi#30]
Banco de dados é um conjunto lógico de informações específicas, organizadas e armazenadas, para serem consultadas ou alteradas quando for necessário, facilitando a tomada de decisões das organizações, e permitindo que diversos setores conversem entre si através do banco de dados.
Portanto um banco de dados não é um conjunto de informações aleatórias, ele é planejado e construído para atender um grupo específico de usuários.

**Comment by plinioleitao** [comment]
Tópico 02, em vez de Tópico <02>.
COM APROVEITAMENTO.
